# Translations template for glance.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 2014.2.0.dev14.g3345d5b\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-10-08 14:13+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/location.py:84
msgid "Invalid location"
msgstr ""

#: glance/location.py:296
msgid "Invalid locations"
msgstr ""

#: glance/location.py:302
#, python-format
msgid "Original locations is not empty: %s"
msgstr ""

#: glance/location.py:373 glance/common/exception.py:332
msgid "No image data could be found"
msgstr ""

#: glance/location.py:385
#, python-format
msgid "Get image %(id)s data failed: %(err)s."
msgstr ""

#: glance/notifier.py:183
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr ""

#: glance/notifier.py:200 glance/api/v1/upload_utils.py:197
#: glance/api/v2/image_data.py:116
#, python-format
msgid "Image storage media is full: %s"
msgstr ""

#: glance/notifier.py:205 glance/api/v1/upload_utils.py:206
#: glance/api/v2/image_data.py:140
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr ""

#: glance/notifier.py:210
#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:217
#, python-format
msgid "Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:224
#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:230
#, python-format
msgid ""
"Image %(image_id)s could not be found after upload. The image may have "
"been deleted during the upload: %(error)s"
msgstr ""

#: glance/notifier.py:238
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"
msgstr ""

#: glance/notifier.py:245
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to internal error:"
" %(error)s"
msgstr ""

#: glance/schema.py:62
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr ""

#: glance/scrubber.py:44
msgid ""
"Directory that the scrubber will use to track information about what to "
"delete. Make sure this is set in glance-api.conf and glance-"
"scrubber.conf."
msgstr ""

#: glance/scrubber.py:49
msgid "The amount of time in seconds to delay before performing a delete."
msgstr ""

#: glance/scrubber.py:52
msgid ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."
msgstr ""

#: glance/scrubber.py:57
msgid "Turn on/off delayed delete."
msgstr ""

#: glance/scrubber.py:59
msgid ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."
msgstr ""

#: glance/scrubber.py:65
msgid "Loop time between checking for new items to schedule for delete."
msgstr ""

#: glance/scrubber.py:73
msgid ""
"Run as a long-running process. When not specified (the default) run the "
"scrub operation once and then exits. When specified do not exit and run "
"scrub on wakeup_time interval as specified in the config."
msgstr ""

#: glance/scrubber.py:570
#, python-format
msgid "%s file is not exists."
msgstr ""

#: glance/scrubber.py:575
#, python-format
msgid "%s file contains conflicting cleanup timestamp."
msgstr ""

#: glance/api/authorization.py:129 glance/api/authorization.py:140
#, python-format
msgid "You cannot get image member for %s"
msgstr ""

#: glance/api/authorization.py:148
#, python-format
msgid "You cannot delete image member for %s"
msgstr ""

#: glance/api/authorization.py:157
#, python-format
msgid "You cannot add image member for %s"
msgstr ""

#: glance/api/authorization.py:166
#, python-format
msgid "You cannot update image member %s"
msgstr ""

#: glance/api/authorization.py:185
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr ""

#: glance/api/authorization.py:203
msgid "You are not permitted to create image members for the image."
msgstr ""

#: glance/api/authorization.py:208 glance/api/authorization.py:399
msgid "Public images do not have members."
msgstr ""

#: glance/api/authorization.py:224
#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr ""

#: glance/api/authorization.py:234
msgid "You are not permitted to modify locations for this image."
msgstr ""

#: glance/api/authorization.py:258
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr ""

#: glance/api/authorization.py:262
msgid "You are not permitted to modify this image."
msgstr ""

#: glance/api/authorization.py:275
msgid "You are not permitted to modify tags on this image."
msgstr ""

#: glance/api/authorization.py:316
msgid "You are not permitted to delete this image."
msgstr ""

#: glance/api/authorization.py:327
msgid "You are not permitted to upload data for this image."
msgstr ""

#: glance/api/authorization.py:364 glance/api/authorization.py:368
#: glance/api/authorization.py:372
msgid "You are not permitted to set status on this task."
msgstr ""

#: glance/api/authorization.py:431
#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr ""

#: glance/api/authorization.py:496
msgid "You are not permitted to delete this namespace."
msgstr ""

#: glance/api/authorization.py:500
msgid "You are not permitted to update this namespace."
msgstr ""

#: glance/api/authorization.py:526
#, python-format
msgid "You are not permitted to create namespace owned by '%s'"
msgstr ""

#: glance/api/authorization.py:585
msgid "You are not permitted to delete this object."
msgstr ""

#: glance/api/authorization.py:589
msgid "You are not permitted to update this object."
msgstr ""

#: glance/api/authorization.py:614
#, python-format
msgid "You are not permitted to create object owned by '%s'"
msgstr ""

#: glance/api/authorization.py:677
msgid "You are not permitted to delete this meta_resource_type."
msgstr ""

#: glance/api/authorization.py:703
#, python-format
msgid "You are not permitted to create resource_type owned by '%s'"
msgstr ""

#: glance/api/authorization.py:757
msgid "You are not permitted to delete this property."
msgstr ""

#: glance/api/authorization.py:761
msgid "You are not permitted to update this property."
msgstr ""

#: glance/api/authorization.py:786
#, python-format
msgid "You are not permitted to create property owned by '%s'"
msgstr ""

#: glance/api/common.py:64
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr ""

#: glance/api/policy.py:34
msgid "The location of the policy file."
msgstr ""

#: glance/api/policy.py:36
msgid "The default policy to use."
msgstr ""

#: glance/api/policy.py:96
msgid "Unable to find policy file"
msgstr ""

#: glance/api/policy.py:220 glance/quota/__init__.py:355
#, python-format
msgid "Invalid locations: %s"
msgstr ""

#: glance/api/middleware/context.py:28
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""

#: glance/api/middleware/context.py:33
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: glance/api/middleware/context.py:36
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""

#: glance/api/middleware/context.py:52
msgid "Unable to retrieve request id from context"
msgstr ""

#: glance/api/middleware/context.py:109
msgid "Invalid service catalog json."
msgstr ""

#: glance/api/middleware/version_negotiation.py:41
#, python-format
msgid "Determining version of request: %(method)s %(path)s Accept: %(accept)s"
msgstr ""

#: glance/api/v1/controller.py:84
#, python-format
msgid "Store for image_id not found: %s"
msgstr ""

#: glance/api/v1/images.py:74
#, python-format
msgid "Invalid disk format '%s' for image."
msgstr ""

#: glance/api/v1/images.py:79
#, python-format
msgid "Invalid container format '%s' for image."
msgstr ""

#: glance/api/v1/images.py:84
#, python-format
msgid "Image name too long: %d"
msgstr ""

#: glance/api/v1/images.py:95
msgid ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."
msgstr ""

#: glance/api/v1/images.py:175
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(num)s, Maximum: %(quota)s"
msgstr ""

#: glance/api/v1/images.py:338
msgid "This operation is currently not permitted on Glance images details."
msgstr ""

#: glance/api/v1/images.py:389
#, python-format
msgid "Bad value passed to filter %(filter)s got %(val)s"
msgstr ""

#: glance/api/v1/images.py:561
#, python-format
msgid "Failed to reserve image. Got error: %s"
msgstr ""

#: glance/api/v1/images.py:864
msgid "Forbidden to update deleted image."
msgstr ""

#: glance/api/v1/images.py:875
#, python-format
msgid "Forbidden to modify '%s' of active image."
msgstr ""

#: glance/api/v1/images.py:893
msgid "Cannot upload to an unqueued image"
msgstr ""

#: glance/api/v1/images.py:917
msgid "Attempted to update Location field for an image not in queued status."
msgstr ""

#: glance/api/v1/images.py:964
#, python-format
msgid "Failed to find image to update: %s"
msgstr ""

#: glance/api/v1/images.py:972
#, python-format
msgid "Forbidden to update image: %s"
msgstr ""

#: glance/api/v1/images.py:1059
#, python-format
msgid "Failed to find image to delete: %s"
msgstr ""

#: glance/api/v1/images.py:1067
#, python-format
msgid "Forbidden to delete image: %s"
msgstr ""

#: glance/api/v1/images.py:1138 glance/api/v1/upload_utils.py:216
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr ""

#: glance/api/v1/members.py:40 glance/registry/api/v1/members.py:34
msgid "No authenticated user"
msgstr ""

#: glance/api/v1/members.py:52
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr ""

#: glance/api/v1/members.py:116 glance/common/exception.py:282
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image members for "
"this image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/api/v1/upload_utils.py:127
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""

#: glance/api/v1/upload_utils.py:226
#, python-format
msgid "Denying attempt to upload image because it exceeds the .quota: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:255
#, python-format
msgid "Failed to upload image %s"
msgstr ""

#: glance/api/v2/image_data.py:78
#, python-format
msgid ""
"Image %(id)s could not be found after upload.The image may have been "
"deleted during the upload: %(error)s Cleaning up the chunks uploaded"
msgstr ""

#: glance/api/v2/image_data.py:124
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr ""

#: glance/api/v2/image_data.py:132
#, python-format
msgid "The incoming image is too large: %s"
msgstr ""

#: glance/api/v2/image_members.py:192 glance/api/v2/images.py:301
#: glance/api/v2/metadef_namespaces.py:356 glance/api/v2/metadef_objects.py:225
#: glance/api/v2/metadef_properties.py:157
#: glance/api/v2/metadef_resource_types.py:145
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:148
msgid "Body expected in request."
msgstr ""

#: glance/api/v2/image_members.py:203
msgid "Member to be added not specified"
msgstr ""

#: glance/api/v2/image_members.py:206
msgid "Member can't be empty"
msgstr ""

#: glance/api/v2/image_members.py:215
msgid "Status not specified"
msgstr ""

#: glance/api/v2/image_members.py:270
msgid "An identifier for the image member (tenantId)"
msgstr ""

#: glance/api/v2/image_members.py:274 glance/api/v2/images.py:682
msgid "An identifier for the image"
msgstr ""

#: glance/api/v2/image_members.py:280
msgid "Date and time of image member creation"
msgstr ""

#: glance/api/v2/image_members.py:287
msgid "Date and time of last modification of image member"
msgstr ""

#: glance/api/v2/image_members.py:292
msgid "The status of this image member"
msgstr ""

#: glance/api/v2/images.py:162 glance/api/v2/images.py:190
#, python-format
msgid "Property %s does not exist."
msgstr ""

#: glance/api/v2/images.py:174
#, python-format
msgid "Property %s already present."
msgstr ""

#: glance/api/v2/images.py:185
#, python-format
msgid "Property %s may not be removed."
msgstr ""

#: glance/api/v2/images.py:203
#, python-format
msgid "Failed to find image %(image_id)s to delete"
msgstr ""

#: glance/api/v2/images.py:227
msgid "Cannot replace locations from a non-empty list to a non-empty list."
msgstr ""

#: glance/api/v2/images.py:251
msgid "Invalid position for adding a location."
msgstr ""

#: glance/api/v2/images.py:267
msgid "Invalid position for removing a location."
msgstr ""

#: glance/api/v2/images.py:309 glance/api/v2/images.py:415
#: glance/api/v2/metadef_namespaces.py:364 glance/api/v2/metadef_objects.py:289
#: glance/api/v2/metadef_properties.py:165
#: glance/api/v2/metadef_resource_types.py:153
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:156
#, python-format
msgid "Attribute '%s' is read-only."
msgstr ""

#: glance/api/v2/images.py:340 glance/api/v2/images.py:362
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr ""

#: glance/api/v2/images.py:348
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."
msgstr ""

#: glance/api/v2/images.py:353
msgid ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."
msgstr ""

#: glance/api/v2/images.py:390
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr ""

#: glance/api/v2/images.py:393
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr ""

#: glance/api/v2/images.py:396
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr ""

#: glance/api/v2/images.py:399
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr ""

#: glance/api/v2/images.py:402
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""

#: glance/api/v2/images.py:408
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr ""

#: glance/api/v2/images.py:418
#, python-format
msgid "Attribute '%s' is reserved."
msgstr ""

#: glance/api/v2/images.py:448
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr ""

#: glance/api/v2/images.py:460
msgid "Unrecognized JSON Schema draft version"
msgstr ""

#: glance/api/v2/images.py:482
msgid "Request body must be a JSON array of operation objects."
msgstr ""

#: glance/api/v2/images.py:487
msgid "Operations must be JSON objects."
msgstr ""

#: glance/api/v2/images.py:509 glance/api/v2/metadef_namespaces.py:411
#: glance/api/v2/tasks.py:172 glance/registry/api/v1/images.py:265
msgid "limit param must be an integer"
msgstr ""

#: glance/api/v2/images.py:513 glance/api/v2/metadef_namespaces.py:415
#: glance/api/v2/tasks.py:176 glance/registry/api/v1/images.py:268
msgid "limit param must be positive"
msgstr ""

#: glance/api/v2/images.py:520 glance/api/v2/metadef_namespaces.py:393
#: glance/api/v2/metadef_objects.py:271 glance/api/v2/tasks.py:142
#, python-format
msgid "Invalid sort direction: %s"
msgstr ""

#: glance/api/v2/images.py:527
#, python-format
msgid "Invalid status: %s"
msgstr ""

#: glance/api/v2/images.py:536 glance/api/v2/metadef_namespaces.py:402
#: glance/api/v2/metadef_objects.py:280
#, python-format
msgid "Invalid visibility value: %s"
msgstr ""

#: glance/api/v2/images.py:540
msgid "The \"changes-since\" filter is no longer available on v2."
msgstr ""

#: glance/api/v2/images.py:688
msgid "Descriptive name for the image"
msgstr ""

#: glance/api/v2/images.py:693
msgid "Status of the image (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:699
msgid "Scope of image accessibility"
msgstr ""

#: glance/api/v2/images.py:704
msgid "If true, image will not be deletable."
msgstr ""

#: glance/api/v2/images.py:708
msgid "md5 hash of image contents. (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:713
msgid "Owner of the image"
msgstr ""

#: glance/api/v2/images.py:718
msgid "Size of image file in bytes (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:722
msgid "Virtual size of image in bytes (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:726
msgid "Format of the container"
msgstr ""

#: glance/api/v2/images.py:731
msgid "Format of the disk"
msgstr ""

#: glance/api/v2/images.py:736
msgid "Date and time of image registration (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:744
msgid "Date and time of the last image modification (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:750
msgid "List of strings related to the image"
msgstr ""

#: glance/api/v2/images.py:758
msgid "URL to access the image file kept in external store (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:763
msgid "Amount of ram (in MB) required to boot image."
msgstr ""

#: glance/api/v2/images.py:767
msgid "Amount of disk space (in GB) required to boot image."
msgstr ""

#: glance/api/v2/images.py:797
msgid "A set of URLs to access the image file kept in external store"
msgstr ""

#: glance/api/v2/metadef_namespaces.py:618
msgid "The unique namespace text."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:623
msgid "The user friendly name for the namespace. Used by UI if available."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:629
msgid "Provides a user friendly description of the namespace."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:635
msgid "Scope of namespace accessibility."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:640
msgid "If true, namespace will not be deletable."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:644
msgid "Owner of the namespace."
msgstr ""

#: glance/api/v2/metadef_namespaces.py:649
msgid "Date and time of namespace creation (READ-ONLY)"
msgstr ""

#: glance/api/v2/metadef_namespaces.py:655
msgid "Date and time of the last namespace modification (READ-ONLY)"
msgstr ""

#: glance/api/v2/metadef_objects.py:184
msgid "Date and time of object creation (READ-ONLY)"
msgstr ""

#: glance/api/v2/metadef_objects.py:190
msgid "Date and time of the last object modification (READ-ONLY)"
msgstr ""

#: glance/api/v2/metadef_resource_types.py:199
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:203
msgid ""
"Resource type names should be aligned with Heat resource types whenever "
"possible: "
"http://docs.openstack.org/developer/heat/template_guide/openstack.html"
msgstr ""

#: glance/api/v2/metadef_resource_types.py:207
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:211
msgid ""
"Specifies the prefix to use for the given resource type. Any properties "
"in the namespace should be prefixed with this prefix when being applied "
"to the specified resource type. Must include prefix separator (e.g. a "
"colon :)."
msgstr ""

#: glance/api/v2/metadef_resource_types.py:216
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:220
msgid ""
"Some resource types allow more than one key / value pair per instance.  "
"For example, Cinder allows user and image metadata on volumes. Only the "
"image properties metadata is evaluated by Nova (scheduling or drivers). "
"This property allows a namespace target to remove the ambiguity."
msgstr ""

#: glance/api/v2/metadef_resource_types.py:227
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:231
msgid "Date and time of resource type association (READ-ONLY)"
msgstr ""

#: glance/api/v2/metadef_resource_types.py:233
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:237
msgid ""
"Date and time of the last resource type association modification (READ-"
"ONLY)"
msgstr ""

#: glance/api/v2/tasks.py:122
msgid ""
"This operation is currently not permitted on Glance Tasks. They are auto "
"deleted after reaching the time based on their expires_at property."
msgstr ""

#: glance/api/v2/tasks.py:136
msgid "Body expected in request"
msgstr ""

#: glance/api/v2/tasks.py:151
#, python-format
msgid "Invalid status value: %s"
msgstr ""

#: glance/api/v2/tasks.py:157
#, python-format
msgid "Invalid type value: %s"
msgstr ""

#: glance/api/v2/tasks.py:164 glance/registry/api/v1/images.py:277
msgid "Invalid marker format"
msgstr ""

#: glance/api/v2/tasks.py:185
#, python-format
msgid "Task '%s' is required"
msgstr ""

#: glance/api/v2/tasks.py:308
msgid "An identifier for the task"
msgstr ""

#: glance/api/v2/tasks.py:309
msgid ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0"
"-9a-fA-F]){12}$"
msgstr ""

#: glance/api/v2/tasks.py:314
msgid "The type of task represented by this content"
msgstr ""

#: glance/api/v2/tasks.py:321
msgid "The current status of this task"
msgstr ""

#: glance/api/v2/tasks.py:331
msgid "The parameters required by task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:335
msgid "The result of current task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:339
msgid "An identifier for the owner of this task"
msgstr ""

#: glance/api/v2/tasks.py:343
msgid ""
"Human-readable informative message only included when appropriate "
"(usually on failure)"
msgstr ""

#: glance/api/v2/tasks.py:348
msgid "Datetime when this resource would be subject to removal"
msgstr ""

#: glance/api/v2/tasks.py:353
msgid "Datetime when this resource was created"
msgstr ""

#: glance/api/v2/tasks.py:357
msgid "Datetime when this resource was updated"
msgstr ""

#: glance/cmd/control.py:102
#, python-format
msgid "%(serv)s appears to already be running: %(pid)s"
msgstr ""

#: glance/cmd/control.py:106
#, python-format
msgid "Removing stale pid file %s"
msgstr ""

#: glance/cmd/control.py:115
msgid "Unable to increase file descriptor limit.  Running as non-root?"
msgstr ""

#: glance/cmd/control.py:160
#, python-format
msgid "%(verb)sing %(serv)s"
msgstr ""

#: glance/cmd/control.py:175
#, python-format
msgid "unable to launch %(serv)s. Got error: %(e)s"
msgstr ""

#: glance/cmd/control.py:206
#, python-format
msgid "%(serv)s (pid %(pid)s) is running..."
msgstr ""

#: glance/cmd/control.py:209
#, python-format
msgid "%s is stopped"
msgstr ""

#: glance/cmd/control.py:225
#, python-format
msgid ""
"Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"
msgstr ""

#: glance/cmd/control.py:255
#, python-format
msgid "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr ""

#: glance/cmd/control.py:259
#, python-format
msgid "Process %d not running"
msgstr ""

#: glance/cmd/control.py:266
#, python-format
msgid "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"
msgstr ""

#: glance/cmd/control.py:269
#, python-format
msgid "%s is already stopped"
msgstr ""

#: glance/cmd/control.py:346
#, python-format
msgid "Suppressed respawn as %(serv)s was %(rsn)s."
msgstr ""

#: glance/cmd/replicator.py:58
#, python-format
msgid ""
"The image %s is already present on the slave, but our check for it did "
"not find it. This indicates that we do not have permissions to see all "
"the images on the slave server."
msgstr ""

#: glance/cmd/replicator.py:283 glance/cmd/replicator.py:315
#: glance/cmd/replicator.py:387 glance/cmd/replicator.py:463
#: glance/cmd/replicator.py:534
msgid "Too few arguments."
msgstr ""

#: glance/cmd/replicator.py:299
#, python-format
msgid "Total size is %(size)d bytes across %(img_count)d images"
msgstr ""

#: glance/cmd/replicator.py:683
#, python-format
msgid "Unknown command: %s"
msgstr ""

#: glance/common/auth.py:186 glance/common/auth.py:226
#, python-format
msgid "Unexpected response: %s"
msgstr ""

#: glance/common/auth.py:254
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr ""

#: glance/common/auth.py:275
#, python-format
msgid "Encountered service with no \"type\": %s"
msgstr ""

#: glance/common/client.py:242
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""

#: glance/common/client.py:250
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""

#: glance/common/client.py:259
#, python-format
msgid "The key file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:266
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:273
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:412
#, python-format
msgid "Constructed URL: %s"
msgstr ""

#: glance/common/config.py:34
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""

#: glance/common/config.py:40
msgid "Name of the paste configuration file."
msgstr ""

#: glance/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr ""

#: glance/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr ""

#: glance/common/config.py:60
msgid "Time in hours for which a task lives after, either succeeding or failing"
msgstr ""

#: glance/common/config.py:66
msgid "Specifies which task executor to be used to run the task scripts."
msgstr ""

#: glance/common/config.py:70
msgid ""
"Specifies the maximum number of eventlet threads which can be spun up by "
"the eventlet based task executor to perform execution of Glance tasks."
msgstr ""

#: glance/common/config.py:77
msgid ""
"DEPRECATED. TO BE REMOVED IN THE JUNO RELEASE. Whether or not to enforce "
"that all DB tables have charset utf8. If your database tables do not have"
" charset utf8 you will need to convert before this option is removed. "
"This option is only relevant if your database engine is MySQL."
msgstr ""

#: glance/common/config.py:86
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""

#: glance/common/config.py:89
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance/common/config.py:92
msgid ""
"Maximum number of properties allowed on an image. Negative values "
"evaluate to unlimited."
msgstr ""

#: glance/common/config.py:95
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance/common/config.py:98
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate"
" to unlimited."
msgstr ""

#: glance/common/config.py:101
msgid "Python module path of data access API"
msgstr ""

#: glance/common/config.py:103
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""

#: glance/common/config.py:106
msgid "Maximum permissible number of items that could be returned by a request"
msgstr ""

#: glance/common/config.py:109
msgid ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can be a security risk, so use "
"this setting with caution!"
msgstr ""

#: glance/common/config.py:114
msgid ""
"Whether to include the backend image locations in image properties. "
"Revealing storage location can be a security risk, so use this setting "
"with caution!  The overrides show_image_direct_url."
msgstr ""

#: glance/common/config.py:119
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."
msgstr ""

#: glance/common/config.py:122
msgid ""
"Set a system wide quota for every user. This value is the total capacity "
"that a user can use across all storage systems. A value of 0 means "
"unlimited.Optional unit can be specified for the value. Accepted units "
"are B, KB, MB, GB and TB representing Bytes, KiloBytes, MegaBytes, "
"GigaBytes and TeraBytesrespectively. If no unit is specified then Bytes "
"is assumed. Note that there should not be any space between value and "
"unit and units are case sensitive."
msgstr ""

#: glance/common/config.py:132
msgid "Deploy the v1 OpenStack Images API."
msgstr ""

#: glance/common/config.py:134
msgid "Deploy the v2 OpenStack Images API."
msgstr ""

#: glance/common/config.py:136
msgid "Deploy the v1 OpenStack Registry API."
msgstr ""

#: glance/common/config.py:138
msgid "Deploy the v2 OpenStack Registry API."
msgstr ""

#: glance/common/config.py:140
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr ""

#: glance/common/config.py:143
msgid "The port on which a pydev process is listening for connections."
msgstr ""

#: glance/common/config.py:146
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""

#: glance/common/config.py:205
#, python-format
msgid "Unable to locate paste config file for %s."
msgstr ""

#: glance/common/config.py:244
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""

#: glance/common/exception.py:38
msgid "An unknown exception occurred"
msgstr ""

#: glance/common/exception.py:63
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: glance/common/exception.py:67
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: glance/common/exception.py:72
msgid "An object with the specified identifier was not found."
msgstr ""

#: glance/common/exception.py:76
msgid "The Store URI was malformed."
msgstr ""

#: glance/common/exception.py:80
msgid "An object with the same identifier already exists."
msgstr ""

#: glance/common/exception.py:84
msgid "An object with the same identifier is currently being operated on."
msgstr ""

#: glance/common/exception.py:89
#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""

#: glance/common/exception.py:94
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: glance/common/exception.py:98
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: glance/common/exception.py:102
msgid "Authorization failed."
msgstr ""

#: glance/common/exception.py:106
msgid "You are not authenticated."
msgstr ""

#: glance/common/exception.py:110 glance/common/exception.py:114
#: glance/common/exception.py:373
msgid "You are not authorized to complete this action."
msgstr ""

#: glance/common/exception.py:118
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:122
#, python-format
msgid ""
"Metadata definition namespace %(namespace)s is protected and cannot be "
"deleted."
msgstr ""

#: glance/common/exception.py:127
#, python-format
msgid ""
"Metadata definition property %(property_name)s is protected and cannot be"
" deleted."
msgstr ""

#: glance/common/exception.py:132
#, python-format
msgid ""
"Metadata definition object %(object_name)s is protected and cannot be "
"deleted."
msgstr ""

#: glance/common/exception.py:137
#, python-format
msgid ""
"Metadata definition resource-type-association %(resource_type)s is "
"protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:142
#, python-format
msgid ""
"Metadata definition resource-type %(resource_type_name)s is a seeded-"
"system type and cannot be deleted."
msgstr ""

#: glance/common/exception.py:147
msgid "Data supplied was not valid."
msgstr ""

#: glance/common/exception.py:151
msgid "Sort key supplied was not valid."
msgstr ""

#: glance/common/exception.py:155
msgid "Invalid configuration in property protection file."
msgstr ""

#: glance/common/exception.py:159
msgid "Invalid configuration in glance-swift conf file."
msgstr ""

#: glance/common/exception.py:163
msgid "Unable to filter using the specified range."
msgstr ""

#: glance/common/exception.py:167
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr ""

#: glance/common/exception.py:171
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr ""

#: glance/common/exception.py:175
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: glance/common/exception.py:179
msgid "There was an error connecting to a server"
msgstr ""

#: glance/common/exception.py:183
msgid "There was an error configuring the client."
msgstr ""

#: glance/common/exception.py:187
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:193
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:204
msgid ""
"The request returned 503 Service Unavailable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: glance/common/exception.py:215
msgid "The request returned 500 Internal Server Error."
msgstr ""

#: glance/common/exception.py:219
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:224
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: glance/common/exception.py:228
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""

#: glance/common/exception.py:233
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: glance/common/exception.py:238
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: glance/common/exception.py:242
msgid "Received invalid HTTP redirect."
msgstr ""

#: glance/common/exception.py:246
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr ""

#: glance/common/exception.py:250
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: glance/common/exception.py:256
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: glance/common/exception.py:260
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: glance/common/exception.py:264
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""

#: glance/common/exception.py:269
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: glance/common/exception.py:273
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."
msgstr ""

#: glance/common/exception.py:278
msgid "The provided image is too large."
msgstr ""

#: glance/common/exception.py:288
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:293
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image tags. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:298
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:303
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr ""

#: glance/common/exception.py:307
msgid "An unknown task exception occurred"
msgstr ""

#: glance/common/exception.py:311
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr ""

#: glance/common/exception.py:315
#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr ""

#: glance/common/exception.py:319
#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr ""

#: glance/common/exception.py:323
#, python-format
msgid "Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""

#: glance/common/exception.py:328
#, python-format
msgid "The location %(location)s already exists"
msgstr ""

#: glance/common/exception.py:336
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr ""

#: glance/common/exception.py:341
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not "
"allowed"
msgstr ""

#: glance/common/exception.py:346
#, python-format
msgid "The metadata definition namespace=%(namespace_name)s already exists."
msgstr ""

#: glance/common/exception.py:351
#, python-format
msgid ""
"A metadata definition object with name=%(object_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:356
#, python-format
msgid ""
"A metadata definition property with name=%(property_name)s already exists"
" in namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:361
#, python-format
msgid ""
"A metadata definition resource-type with name=%(resource_type_name)s "
"already exists."
msgstr ""

#: glance/common/exception.py:366
#, python-format
msgid ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s already "
"exists."
msgstr ""

#: glance/common/exception.py:377
#, python-format
msgid ""
"The metadata definition %(record_type)s with name=%(record_name)s not "
"deleted. Other records still refer to it."
msgstr ""

#: glance/common/exception.py:383
#, python-format
msgid "Metadata definition namespace=%(namespace_name)swas not found."
msgstr ""

#: glance/common/exception.py:388
#, python-format
msgid ""
"The metadata definition object with name=%(object_name)s was not found in"
" namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:394
#, python-format
msgid ""
"The metadata definition property with name=%(property_name)s was not "
"found in namespace=%(namespace_name)s."
msgstr ""

#: glance/common/exception.py:400
#, python-format
msgid ""
"The metadata definition resource-type with name=%(resource_type_name)s, "
"was not found."
msgstr ""

#: glance/common/exception.py:405
#, python-format
msgid ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s, was not "
"found."
msgstr ""

#: glance/common/exception.py:412
#, python-format
msgid "Metadata definition %(record_type)s record not found for id %(id)s."
msgstr ""

#: glance/common/property_utils.py:36
msgid "The location of the property protection file."
msgstr ""

#: glance/common/property_utils.py:39
msgid ""
"This config value indicates whether \"roles\" or \"policies\" are used in"
" the property protection file."
msgstr ""

#: glance/common/property_utils.py:74
#, python-format
msgid "Couldn't find property protection file %(file)s: %(error)s."
msgstr ""

#: glance/common/property_utils.py:81
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:100
#, python-format
msgid ""
"Multiple policies '%s' not allowedfor a given operation. Policies can be "
"combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:113
#, python-format
msgid ""
"Malformed property protection rule in [%(prop)s] %(op)s=%(perm)s: '@' and"
" '!' are mutually exclusive"
msgstr ""

#: glance/common/property_utils.py:126
#, python-format
msgid ""
"Property protection on operation %(operation)s for rule %(rule)s is not "
"found. No role will be allowed to perform this operation."
msgstr ""

#: glance/common/property_utils.py:138
#, python-format
msgid "Encountered a malformed property protection rule %(rule)s: %(error)s."
msgstr ""

#: glance/common/rpc.py:140
msgid "Request must be a list of commands"
msgstr ""

#: glance/common/rpc.py:145
#, python-format
msgid "Bad Command: %s"
msgstr ""

#: glance/common/rpc.py:152
#, python-format
msgid "Wrong command structure: %s"
msgstr ""

#: glance/common/rpc.py:161
msgid "Command not found"
msgstr ""

#: glance/common/rpc.py:183
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/store_utils.py:33 glance/registry/client/__init__.py:43
msgid ""
"Whether to pass through the user token when making requests to the "
"registry."
msgstr ""

#: glance/common/swift_store_utils.py:29
msgid ""
"The reference to the default swift account/backing store parameters to "
"use for adding new images."
msgstr ""

#: glance/common/swift_store_utils.py:32
msgid ""
"The address where the Swift authentication service is "
"listening.(deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:35
msgid ""
"The user to authenticate against the Swift authentication service "
"(deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:38
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service. (deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:41
msgid "The config file that has the swift account(s)configs."
msgstr ""

#: glance/common/swift_store_utils.py:83
#, python-format
msgid "swift config file %(conf_file)s:%(exc)s not found"
msgstr ""

#: glance/common/swift_store_utils.py:97
msgid "Invalid format of swift store configcfg"
msgstr ""

#: glance/common/utils.py:111
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr ""

#: glance/common/utils.py:243
#, python-format
msgid "Bad header: %(header_name)s"
msgstr ""

#: glance/common/utils.py:253
#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr ""

#: glance/common/utils.py:260
#, python-format
msgid "Image %(key)s must be >= 0 ('%(value)s' specified)."
msgstr ""

#: glance/common/utils.py:454
msgid ""
"Error setting up the debug environment.  Verify that the option "
"pydev_worker_debug_host is pointing to a valid hostname or IP on which a "
"pydev server is listening on the port indicated by "
"pydev_worker_debug_port."
msgstr ""

#: glance/common/utils.py:491
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: glance/common/utils.py:524
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  "
"Please verify it.  Error: %(ioe)s"
msgstr ""

#: glance/common/utils.py:531
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  "
"Please verify it. OpenSSL error: %(ce)s"
msgstr ""

#: glance/common/utils.py:545
#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""

#: glance/common/utils.py:623
#, python-format
msgid "Host and port \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:626
#, python-format
msgid "Port \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:635
#, python-format
msgid "Host \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:638
#, python-format
msgid ""
"%s Please specify a host:port pair, where host is an IPv4 address, IPv6 "
"address, hostname, or FQDN. If using an IPv6 address, enclose it in "
"brackets separately from the port (i.e., \"[fe80::a:b:c]:9876\")."
msgstr ""

#: glance/common/wsgi.py:55
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""

#: glance/common/wsgi.py:58
msgid "The port on which the server will listen."
msgstr ""

#: glance/common/wsgi.py:63
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr ""

#: glance/common/wsgi.py:66
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in "
"seconds that the connection must be idle before TCP starts sending "
"keepalive probes."
msgstr ""

#: glance/common/wsgi.py:69
msgid "CA certificate file to use to verify connecting clients."
msgstr ""

#: glance/common/wsgi.py:71
msgid "Certificate file to use when starting API server securely."
msgstr ""

#: glance/common/wsgi.py:73
msgid "Private key file to use when starting API server securely."
msgstr ""

#: glance/common/wsgi.py:79
msgid ""
"The number of child process workers that will be created to service "
"requests. The default will be equal to the number of CPUs available."
msgstr ""

#: glance/common/wsgi.py:83
msgid ""
"Name of eventlet hub to use. Traditionally, we have only supported "
"'poll', however 'selects' may be appropriate for some platforms. See "
"http://eventlet.net/doc/hubs.html for more details."
msgstr ""

#: glance/common/wsgi.py:88
msgid ""
"Maximum line size of message headers to be accepted. max_header_line may "
"need to be increased when using large tokens (typically those generated "
"by the Keystone v3 API with big service catalogs"
msgstr ""

#: glance/common/wsgi.py:96
msgid "If False fully disable profiling feature."
msgstr ""

#: glance/common/wsgi.py:98
msgid "If False doesn't trace SQL requests."
msgstr ""

#: glance/common/wsgi.py:144
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: glance/common/wsgi.py:182
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: glance/common/wsgi.py:202
#, python-format
msgid "eventlet '%s' hub is not available on this platform"
msgstr ""

#: glance/common/wsgi.py:266
#, python-format
msgid "Starting %d workers"
msgstr ""

#: glance/common/wsgi.py:281
#, python-format
msgid "Removing dead child %s"
msgstr ""

#: glance/common/wsgi.py:284
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr ""

#: glance/common/wsgi.py:288
msgid "All workers have terminated. Exiting"
msgstr ""

#: glance/common/wsgi.py:296
msgid "Caught keyboard interrupt. Exiting."
msgstr ""

#: glance/common/wsgi.py:322
#, python-format
msgid "Child %d exiting normally"
msgstr ""

#: glance/common/wsgi.py:327
#, python-format
msgid "Started child %s"
msgstr ""

#: glance/common/wsgi.py:351
msgid "Starting single process server"
msgstr ""

#: glance/common/wsgi.py:564
#, python-format
msgid "Malformed Content-Range header: %s"
msgstr ""

#: glance/common/wsgi.py:591
msgid "Malformed JSON in request body."
msgstr ""

#: glance/common/location_strategy/__init__.py:25
msgid ""
"This value sets what strategy will be used to determine the image "
"location order. Currently two strategies are packaged with Glance "
"'location_order' and 'store_type'."
msgstr ""

#: glance/common/location_strategy/__init__.py:52
#, python-format
msgid ""
"%(strategy)s is registered as a module twice. %(module)s is not being "
"used."
msgstr ""

#: glance/common/location_strategy/__init__.py:61
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/location_strategy/__init__.py:76
#, python-format
msgid ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"
msgstr ""

#: glance/common/location_strategy/store_type.py:25
msgid ""
"The store names to use to get store preference order. The name must be "
"registered by one of the stores defined by the 'known_stores' config "
"option. This option will be applied when you using 'store_type' option as"
" image location strategy defined by the 'location_strategy' config "
"option."
msgstr ""

#: glance/common/scripts/utils.py:63
#, python-format
msgid "Input does not contain '%(key)s' field"
msgstr ""

#: glance/common/scripts/utils.py:89
#, python-format
msgid "Invalid location: %s"
msgstr ""

#: glance/common/scripts/image_import/main.py:123
#, python-format
msgid ""
"Task ID %(task_id)s: Ignoring property %(k)s for setting base properties "
"while creating Image."
msgstr ""

#: glance/db/__init__.py:71 glance/db/__init__.py:178 glance/db/__init__.py:190
#, python-format
msgid "No image found with ID %s"
msgstr ""

#: glance/db/__init__.py:249
#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr ""

#: glance/db/__init__.py:266
#, python-format
msgid "The specified member %s could not be found"
msgstr ""

#: glance/db/__init__.py:344 glance/db/__init__.py:365
#: glance/db/__init__.py:382 glance/db/simple/api.py:861
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/__init__.py:429
#, python-format
msgid "Could not find namespace %s"
msgstr ""

#: glance/db/__init__.py:451 glance/db/__init__.py:461
#: glance/db/__init__.py:471
#, python-format
msgid "The specified namespace %s could not be found"
msgstr ""

#: glance/db/__init__.py:563
#, python-format
msgid "Could not find metadata object %s"
msgstr ""

#: glance/db/__init__.py:586
#, python-format
msgid "The specified metadata object %s could not be found"
msgstr ""

#: glance/db/__init__.py:666
#, python-format
msgid "The specified resource type %s could not be found "
msgstr ""

#: glance/db/__init__.py:713
#, python-format
msgid "Could not find property %s"
msgstr ""

#: glance/db/__init__.py:735
#, python-format
msgid "The specified property %s could not be found"
msgstr ""

#: glance/db/simple/api.py:50
#, python-format
msgid "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"
msgstr ""

#: glance/db/simple/api.py:55
#, python-format
msgid "Returning %(funcname)s: %(output)s"
msgstr ""

#: glance/db/simple/api.py:273 glance/db/sqlalchemy/api.py:453
msgid "Unable to filter on a range with a non-numeric value."
msgstr ""

#: glance/db/simple/api.py:344
#, python-format
msgid "Could not find image %s"
msgstr ""

#: glance/db/simple/api.py:348
msgid "Unable to get deleted image"
msgstr ""

#: glance/db/simple/api.py:352
msgid "Unable to get unowned image"
msgstr ""

#: glance/db/simple/api.py:444 glance/db/sqlalchemy/api.py:1093
msgid "Image id is required."
msgstr ""

#: glance/db/simple/api.py:502 glance/db/sqlalchemy/api.py:790
#, python-format
msgid "The location data has an invalid ID: %d"
msgstr ""

#: glance/db/simple/api.py:522 glance/db/simple/api.py:548
#: glance/db/sqlalchemy/api.py:812 glance/db/sqlalchemy/api.py:840
#, python-format
msgid "No location found with ID %(loc)s from image %(img)s"
msgstr ""

#: glance/db/simple/api.py:532
msgid ""
"The status of deleted image location can only be set to 'pending_delete' "
"or 'deleted'."
msgstr ""

#: glance/db/simple/api.py:866
#, python-format
msgid "Unable to get deleted task %s"
msgstr ""

#: glance/db/simple/api.py:989
msgid "Task does not exist"
msgstr ""

#: glance/db/simple/api.py:1027
#, python-format
msgid "Could not find task info %s"
msgstr ""

#: glance/db/simple/api.py:1083
#: glance/db/sqlalchemy/metadef_api/namespace.py:255
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition "
"namespace with the same name of %s"
msgstr ""

#: glance/db/simple/api.py:1113
#: glance/db/sqlalchemy/metadef_api/namespace.py:99
#, python-format
msgid "Forbidding request, metadata definition namespace=%s is not visible."
msgstr ""

#: glance/db/simple/api.py:1322
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object"
" with the same name=%(name)s  in namespace=%(namespace_name)s."
msgstr ""

#: glance/db/simple/api.py:1444
#: glance/db/sqlalchemy/metadef_api/property.py:127
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition "
"property with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""

#: glance/db/simple/api.py:1757
#: glance/db/sqlalchemy/metadef_api/namespace.py:123
#, python-format
msgid "Forbidding request, metadata definition namespace=%s not visible."
msgstr ""

#: glance/db/sqlalchemy/api.py:113
msgid "You do not own this image"
msgstr ""

#: glance/db/sqlalchemy/api.py:383
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: glance/db/sqlalchemy/api.py:741
#: glance/tests/unit/v2/test_registry_client.py:500
#, python-format
msgid ""
"cannot transition from %(current)s to %(next)s in update (wanted "
"from_state=%(from)s)"
msgstr ""

#: glance/db/sqlalchemy/api.py:821
msgid ""
"The status of deleted image location can only be set to 'pending_delete' "
"or 'deleted'"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:43
msgid "Path to the directory where json metadata files are stored"
msgstr ""

#: glance/db/sqlalchemy/metadef_api/object.py:116
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object"
" with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:90
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:157
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:127
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:193
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:139
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:205
msgid "Badly formed credentials in Swift URI."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:156
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:222
#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr ""

#: glance/domain/__init__.py:64
#, python-format
msgid "new_image() got unexpected keywords %s"
msgstr ""

#: glance/domain/__init__.py:134
#, python-format
msgid "__init__() got unexpected keyword argument '%s'"
msgstr ""

#: glance/domain/__init__.py:156
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr ""

#: glance/domain/__init__.py:159
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr ""

#: glance/domain/__init__.py:176
msgid "Visibility must be either \"public\" or \"private\""
msgstr ""

#: glance/domain/__init__.py:195
msgid "Attribute container_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:207
msgid "Attribute disk_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:219 glance/domain/__init__.py:232
msgid "Cannot be a negative value"
msgstr ""

#: glance/domain/__init__.py:297
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr ""

#: glance/domain/__init__.py:373
#, python-format
msgid "Task [%(task_id)s] status changing from %(cur_status)s to %(new_status)s"
msgstr ""

#: glance/domain/__init__.py:380
#, python-format
msgid ""
"Task [%(task_id)s] status failed to change from %(cur_status)s to "
"%(new_status)s"
msgstr ""

#: glance/image_cache/__init__.py:39
msgid "The driver to use for image cache management."
msgstr ""

#: glance/image_cache/__init__.py:41
msgid "The maximum size in bytes that the cache can use."
msgstr ""

#: glance/image_cache/__init__.py:43
msgid ""
"The amount of time to let an image remain in the cache without being "
"accessed."
msgstr ""

#: glance/image_cache/__init__.py:46
msgid "Base directory that the Image Cache uses."
msgstr ""

#: glance/image_cache/__init__.py:258
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr ""

#: glance/image_cache/client.py:117
msgid ""
"--os_auth_url option or OS_AUTH_URL environment variable required when "
"keystone authentication strategy is enabled\n"
msgstr ""

#: glance/image_cache/drivers/base.py:54
#, python-format
msgid "Failed to read %s from config"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:44
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:126
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr ""

#: glance/openstack/common/gettextutils.py:320
msgid "Message objects do not support addition."
msgstr ""

#: glance/openstack/common/gettextutils.py:330
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: glance/openstack/common/lockutils.py:102
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: glance/openstack/common/log.py:327
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: glance/openstack/common/log.py:436
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: glance/openstack/common/log.py:486
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: glance/openstack/common/log.py:729
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: glance/openstack/common/policy.py:396
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: glance/openstack/common/policy.py:406
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: glance/openstack/common/policy.py:681
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: glance/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: glance/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: glance/openstack/common/processutils.py:144
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: glance/openstack/common/processutils.py:150
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: glance/openstack/common/processutils.py:247
msgid "Environment not supported over SSH"
msgstr ""

#: glance/openstack/common/processutils.py:251
msgid "process_input not supported over SSH"
msgstr ""

#: glance/openstack/common/strutils.py:92
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: glance/openstack/common/strutils.py:197
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: glance/openstack/common/strutils.py:206
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: glance/registry/__init__.py:25
msgid "Address to find the registry server."
msgstr ""

#: glance/registry/__init__.py:27
msgid "Port the registry server is listening on."
msgstr ""

#: glance/registry/api/v1/images.py:126 glance/registry/api/v1/images.py:131
msgid "Invalid marker. Image could not be found."
msgstr ""

#: glance/registry/api/v1/images.py:235
msgid "Unrecognized changes-since value"
msgstr ""

#: glance/registry/api/v1/images.py:240
msgid "protected must be True, or False"
msgstr ""

#: glance/registry/api/v1/images.py:287
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr ""

#: glance/registry/api/v1/images.py:296
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr ""

#: glance/registry/api/v1/images.py:322
msgid "is_public must be None, True, or False"
msgstr ""

#: glance/registry/api/v1/images.py:416
msgid "Invalid image id format"
msgstr ""

#: glance/registry/api/v1/images.py:431
#, python-format
msgid "Image with identifier %s already exists!"
msgstr ""

#: glance/registry/api/v1/images.py:435
#, python-format
msgid "Failed to add image metadata. Got error: %s"
msgstr ""

#: glance/registry/api/v1/images.py:484
#, python-format
msgid "Failed to update image metadata. Got error: %s"
msgstr ""

#: glance/registry/api/v1/members.py:103
#, python-format
msgid "Image %(id)s not found"
msgstr ""

#: glance/registry/api/v1/members.py:119 glance/registry/api/v1/members.py:237
#: glance/registry/api/v1/members.py:301
msgid "No permission to share that image"
msgstr ""

#: glance/registry/api/v1/members.py:130 glance/registry/api/v1/members.py:147
#: glance/registry/api/v1/members.py:250
#, python-format
msgid "Invalid membership association: %s"
msgstr ""

#: glance/registry/api/v1/members.py:314 glance/registry/api/v1/members.py:339
msgid "Membership could not be found."
msgstr ""

#: glance/registry/api/v2/rpc.py:42
#, python-format
msgid "Registry service can't use %s"
msgstr ""

#: glance/registry/client/__init__.py:20
msgid ""
"The protocol to use for communication with the registry server.  Either "
"http or https."
msgstr ""

#: glance/registry/client/__init__.py:23
msgid "The path to the key file to use in SSL connections to the registry server."
msgstr ""

#: glance/registry/client/__init__.py:26
msgid ""
"The path to the cert file to use in SSL connections to the registry "
"server."
msgstr ""

#: glance/registry/client/__init__.py:29
msgid ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."
msgstr ""

#: glance/registry/client/__init__.py:32
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."
msgstr ""

#: glance/registry/client/__init__.py:36
msgid ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."
msgstr ""

#: glance/registry/client/__init__.py:46
msgid ""
"The administrators user name. If \"use_user_token\" is not in effect, "
"then admin credentials can be specified."
msgstr ""

#: glance/registry/client/__init__.py:50
msgid ""
"The administrators password. If \"use_user_token\" is not in effect, then"
" admin credentials can be specified."
msgstr ""

#: glance/registry/client/__init__.py:54
msgid ""
"The tenant name of the administrative user. If \"use_user_token\" is not "
"in effect, then admin tenant name can be specified."
msgstr ""

#: glance/registry/client/__init__.py:58
msgid ""
"The URL to the keystone service. If \"use_user_token\" is not in effect "
"and using keystone auth, then URL of keystone can be specified."
msgstr ""

#: glance/registry/client/__init__.py:63
msgid ""
"The strategy to use for authentication. If \"use_user_token\" is not in "
"effect, then auth strategy can be specified."
msgstr ""

#: glance/registry/client/__init__.py:67
msgid ""
"The region for the authentication service. If \"use_user_token\" is not "
"in effect and using keystone auth, then region name can be specified."
msgstr ""

#: glance/registry/client/v1/api.py:33
msgid ""
"Whether to pass through headers containing user and tenant information "
"when making requests to the registry. This allows the registry to use the"
" context middleware without keystonemiddleware's auth_token middleware, "
"removing calls to the keystone auth service. It is recommended that when "
"using this option, secure communication between glance api and glance "
"registry is ensured by means other than auth_token middleware."
msgstr ""

#: glance/registry/client/v1/api.py:78 glance/registry/client/v2/api.py:60
msgid "Configuration option was not valid"
msgstr ""

#: glance/registry/client/v1/api.py:82 glance/registry/client/v2/api.py:64
msgid "Could not find required configuration option"
msgstr ""

#: glance/tests/unit/test_migrations.py:929
#, python-format
msgid "location: %s data lost"
msgstr ""

